apiVersion: apps/v1
kind: Deployment

metadata:
  name: oo


spec:
  selector:
    matchLabels:
      app: m
  replicas: 3
  template: 
    metadata:
      name: dep1
      labels:
        app: m
    spec:
      containers:
        - image: eslamgalal123/project
          name: project-container
          imagePullpolicy: IfNotPresent
          ports:
            -containerPort: 80